### ISSUE TITLE
User can't close widgetbar through button 'Close widgetbar'

### ISSUE THREAD

**Issue by Luna-Akkermans** [Marc-Vroegh/pienteren#23]
**Describe the bug**
When attempting to close the widget bar by clicking the 'Close widgetbar' button, the widget bar does not close, but only opens does open the widgetbar when the button is showing 'Show widgetbar'

**To Reproduce**
1. Go to 'dashboard'
2. Look at the sidebar, and press settings.
3. Now click on 'Show widgetbar'
4. Now press 'Close widgetbar'
As you can see it doesn't close now.

**Expected behavior**
We expect the widgetbar to close when the button is pressed to close it.

**Actual behavior**
Text of the button changed, but not the functionality.

**Screenshots**
![afbeelding](https://github.com/Marc-Vroegh/pienteren/assets/70649878/cd88fa8c-4bcf-4b0d-a61b-eacfab7949e7)

**Platform**
Windows 11 pro
Firefox 124.0

**Found in version**
0.1.0

**Comment by Luna-Akkermans** [comment]
I have solved this issue in commit #185d7df 
add javascript functionality to implement this.

**Comment by Marc-Vroegh** [comment]
Thank you for solving the issue, Luna. the user can now close the WidgetBar by pressing the same button for opening it, also the WidgetBar can still be closed by pressing the WidgetBar itself. In terms of the code itself, it looks clean, but you have now used a different method than before, no use of a toggle function.
