### ISSUE TITLE
Text overflow in widget div allows input longer than display area

### ISSUE THREAD

**Issue by Luna-Akkermans** [Marc-Vroegh/pienteren#24]
**Describe the bug**
Users can enter text into the name input field for widgets, that extends beyond the confines of the widget's display area, causing display and usability issues as the text overflows and is not fully visible or scrollable.

**To Reproduce**
1. Go to Dashboard'
2. Click on a widget in the widgetbar
3. Write in the name input field sometrhing long.

**Expected behavior**
It to either restrict length or move down the text.

**Actual behavior**
The text extends beyond the widget's

**Platform**
Windows 11 pro
Firefox 124.0

**Found in version**
0.1.0

**Comment by Marc-Vroegh** [comment]
added an input max length, issue has now been fixed

**Comment by Luna-Akkermans** [comment]
Great fix, super simple well done. Next time it could be a bit more fool proof but really well done
