### ISSUE TITLE
holder disappears for dropping every widget

### ISSUE THREAD

**Issue by Marc-Vroegh** [Marc-Vroegh/pienteren#25]
Describe the bug
if you have styled a widget and added that, the widget gets into a holder which holds it before the user places it on the dashboard, the problem is that this holder also disappears when dropping other widgets in stead of the widget which was placed in the holder

To Reproduce

Go to Dashboard'
Click on a widget in the widgetbar
write text.
select color.
select box.
drag widget
widgets get into holder
move other widget instead of in holder
See error
Expected behavior
holder doesn't disappear unless the widget in holder is dropped

Actual behavior
holder disappears when every widget is dropped

Platform
Mac OS Sonoma
Chrome 23.0.6312.124

Found in version
0.1.0

**Comment by Luna-Akkermans** [comment]
Not relevant anymore after update to dropping widgets
