### ISSUE TITLE
Feedback is not styled correctly and or unreadable when user tries to reset their password.

### ISSUE THREAD

**Issue by Luna-Akkermans** [Marc-Vroegh/pienteren#34]
**Describe the bug**
After a user tries to reset their password or does reset their password, the application feedback about sucess and or fail is in black. 
**To Reproduce**
1. Go to 'Wachtwoord herstellen'
2. Fill in the email
3. See error

**Expected behavior**
Expected to get feedback from the application in a clear way so the user can see it all.

**Actual behavior**
Input feedback is unreadable

**Platform**
Windows 10
Google Chrome 15853.4.0

**Found in version**
0.1.0

**Comment by Marc-Vroegh** [comment]
I have fixed the bug
